### ISSUE TITLE
Native "Go to file" (CMD/CTRL-P) hangs when sandbox FS is enabled

### ISSUE THREAD

**Issue by stevemartina-salesforce** [SqrTT/prophet#309]
**Describe the bug**
Since the Nov 2021 release of VSC, if sandbox FS is enabled two things happen:

- npm scripts section in the Explorer sidebar no longer populates
- native "Go to File..." no longer works - it remembers recent files but cannot search for new ones

In both cases the VSCode "moving underline / spinner" keeps running indefinitely.

**To Reproduce**

1. create new window
2. install and configure Prophet extension
3. disable sandbox FS (you might need to remove the sandbox FS from the workspace manually)
4. save as workspace 
5. quit or reload window
6. add folders to the workspace and set up dw.json
7. invoke "go to file", verify it works normally
8. verify that NPM scripts populates normally in Explorer sidebar
9. from Prophet settings, enable sandbox FS
10. quit or reload
11. verify that sandbox FS is shown in the workspace folders
12. verify that NPM scripts no longer populates
13. invoke "go to file", verify it no longer works

**Expected behavior**
I would expect go to file and NPM scripts section to work normally even when sandbox FS is enabled

**Desktop (please complete the following information):**
 - OS: MacOS Darwin 19.6.0
 - VSCode 1.63.2
 - The extension version v1.4.25

VSCode version info:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

**Comment by syed-shahjahan** [comment]
I'm also facing this issue.

As a temporary solution I have removed the below setting from Settings.JSON file and it started working. Also, I have removed the additional "Sandbox" workspace (which loads the log files and folders) created by this plugin in Explorer

`"extension.prophet.sandbox.filesystem.enabled": false,`

In addition, raised an issue in vscode repo https://github.com/microsoft/vscode/issues/139056

**Comment by jmccarthy-wb** [comment]
I am experiencing an identical issue on Windows 10. "Go To File" works when accessing the same codebase with Prophet disabled.

**Comment by SqrTT** [comment]
Hi all, I'll look at the issue

Currently feels like the same issue https://github.com/microsoft/vscode/issues/94928

**Comment by SqrTT** [comment]
VSCode issue should be fixed in https://github.com/microsoft/vscode/issues/140737

**Comment by jmccarthy-wb** [comment]
This is still an issue for me. [microsoft/vscode#140737](https://github.com/microsoft/vscode/issues/140737) was marked as duplicate and closed, but never actually resolved. [microsoft/vscode#139172](https://github.com/microsoft/vscode/issues/139172) is closed as well.

**Comment by jmccarthy-wb** [comment]
Update: Issue appears resolved at least as of 02.07.22
